name: Build

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: "main"
        description: "Branch to do shit on"

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "25"
          distribution: "graalvm"

      - name: Build binary
        run: ./gradlew nativeCompile

      - name: Rename binary
        shell: bash
        run: |
          mkdir -p dist
          cp build/native/nativeCompile/* dist/

      - name: "Upload!"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*